/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    LangSelect: typeof import('./../src/components/lang-select/index.vue')['default']
    ThemePicker: typeof import('./../src/components/theme-picker/index.vue')['default']
  }
}
